apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-kv
  labels:
    app: minio-kv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-kv
  strategy:
    type: Recreate
  template:
    metadata:
      name: minio-kv
      labels:
        app: minio-kv
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pv-claim
      containers:
      - name: minio
        volumeMounts:
        - name: data
          mountPath: "/data"
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        imagePullPolicy: IfNotPresent
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minio-access-key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minio-secret-key
        args:
          - server
          - /data
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
      - name: minio-kv
        image: utsavanand2/minio-kv:0.1.0
        imagePullPolicy: Always
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minio-access-key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: minio-secret-key
          - name: host
            value: 127.0.0.1:9000
        command:
          - minio-kv
          # - --token=$TOKEN
        ports:
        - containerPort: 8080
          protocol: TCP
